server:
  port: 7083
  
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: AUTH_SERVICE
        uri: lb://AUTH-SERVICE
        predicates:
        - Path= /auth/** # anything like registerUser


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true 
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7084/eureka