server:
  port: 7083
  
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: AUTH-SERVICE
        uri: lb://AUTH-SERVICE
        predicates:
        - Path= /api/auth/**, /api/users/** # anything like registerUser
      - id: RESTAURANT-SERVICE
        uri: lb://RESTAURANT-SERVICE
        predicates:
        - Path= /api/category/**, /api/common/**, /api/restaurant/**, /api/food/**
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE
        predicates:
        - Path= /api/order/**, /api/payment/**
      - id: DELIVERY-AND-CART-SERVICE
        uri: lb://DELIVERY-AND-CART-SERVICE
        predicates:
        - Path= /api/cart/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true 
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7084/eureka