server:
  port: 8092

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Tuktuk@123
  application:
    name: ORDER-SERVICE

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7084/eureka