spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Tuktuk@123


  data:
    redis:
      host: redis-12716.c13.us-east-1-3.ec2.redns.redis-cloud.com
      port: 12716
      username: default
      password: 9VZ3R9COaiFYZGTwXiLDIfx1jZ0fiCPd
  application:
    name: AUTH-SERVICE
server:
  port: 8090
#  servlet:
#    context-path: /auth-service
eureka:
  instance:
    prefer-ip-address: true
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7084/eureka