server:
  port: 8091 #The port of this particular service will run independently
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
# the local database connectivity configuration below
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Tuktuk@123		
  data:
    redis:
      host: redis-18951.c15.us-east-1-4.ec2.redns.redis-cloud.com:18951
      port: 18951
      username: default
      password: mjM8DVtsyuEWbh67nQGB2AuixBnsjhLx