server:
  port: 8093

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Tuktuk@123
  data:
    redis:
      host: xyz
      port: port
      username: default
      password: 9VZGTwXiLDIfx1jZ0fiCPd
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest 
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7084/eureka
