server:
  port: 8094

spring:
  data:
    redis:
      host: XYZ
      port: 123
      username: default
      password: 9VZ3R9CLDIfx1jZ0fiCPd
  application:
    name: DELIVERY-AND-CART-SERVICE
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_and_cart_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Tuktuk@123
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7084/eureka
