server:
  port: 8094

spring:
  data:
    redis:
      host: redis-12716.c13.us-east-1-3.ec2.redns.redis-cloud.com
      port: 12716
      username: default
      password: 9VZ3R9COaiFYZGTwXiLDIfx1jZ0fiCPd
  application:
    name: DELIVERY-AND-CART-SERVICE

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7084/eureka